SELECT *
FROM 직원
GROUP BY 성별
ORDER BY 연봉 DESC;

--제약조건 실습문제

CREATE TABLE QUIZ_TABLE ( -- 객체의 명명.
Q_ID NUMBER(3,0) NOT NULL, -- 컬럼에 NULL 입력 불가
Q_CONTENT VARCHAR2(200) NOT NULL, 
Q_ANSWER VARCHAR2(100),
REG_DATE DATE DEFAULT SYSDATE,
Q_BINGO VARCHAR2(100) DEFAULT 'O'
);

CREATE TABLE 회원정보 (
회원ID VARCHAR(10) NOT NULL,
이름 VARCHAR(20) NOT NULL,
가입일자 DATE DEFAULT SYSDATE,
나이 NUMBER DEFAULT 0
);

CREATE TABLE 회원연락처 (
회원ID VARCHAR(10) NOT NULL,
구분코드 VARCHAR(10) NOT NULL,
연락처 VARCHAR(15) NOT NULL
);

CREATE TABLE 회원주소 (
회원ID VARCHAR2(10) NOT NULL,
도로명주소 VARCHAR2(200) NOT NULL
);

ALTER TABLE 회원정보 ADD CONSTRAINT PK_회원정보 PRIMARY KEY(회원ID);
ALTER TABLE 회원연락처 ADD CONSTRAINT PK_회원연락처 PRIMARY KEY(회원ID, 구분코드);
ALTER TABLE 회원주소 ADD CONSTRAINT PK_회원주소 PRIMARY KEY(회원ID);

ALTER TABLE 회원연락처 ADD CONSTRAINT FK_회원연락처 FOREIGN KEY(회원ID)
REFERENCES 회원정보(회원ID);

ALTER TABLE 회원주소 ADD CONSTRAINT FK_회원주소 FOREIGN KEY(회원ID)
REFERENCES 회원정보(회원ID);

